name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Unit Tests
        run: ./gradlew test

  release:
    name: Create Release Tag
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bump Version and Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Read current version
          CURRENT_VERSION=$(grep -oP 'version = "\K[0-9]+\.[0-9]+\.[0-9]+' composa/build.gradle.kts)

          # Increment version (patch increment)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          # Update version in Gradle file
          awk -v old="version = \"$CURRENT_VERSION\"" -v new="version = \"$NEW_VERSION\"" \
              '{gsub(old, new)}1' composa/build.gradle.kts > temp && mv temp composa/build.gradle.kts

          # Commit and push version update
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add composa/build.gradle.kts
          git commit -m "Bump version to $NEW_VERSION"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}

          # Create and push tag
          git tag $NEW_VERSION
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $NEW_VERSION